version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    ports:
      - "9090:9090"